store/api/urls.py
from django.urls import include, path


app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

store/orders/urls.py
from django.urls import path

from .views import (CanceledTemplateView, OrderCreateView, OrderDetailView,
                    OrderListView, SuccessTemplateView)

app_name = 'orders'


urlpatterns = [
    path('order_create', OrderCreateView.as_view(), name='order_create'),
    path('', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_detail'),
    path('order_success', SuccessTemplateView.as_view(), name='order_success'),
    path(
        'order_canceled', CanceledTemplateView.as_view(), name='order_canceled'
    ),
]

store/products/urls.py
from django.urls import path

from .views import ProductsListView, ProductDetailView, basket_add, basket_update, basket_remove

app_name = 'products'


urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path(
        'category/<int:category_id>/',
        ProductsListView.as_view(),
        name='category'
    ),
    path(
        'baskets/add/<int:product_id>/',
        basket_add,
        name='basket_add'
    ),
    path(
        'baskets/update/<int:product_id>/',
        basket_update,
        name='basket_update'
    ),
    path(
        'baskets/remove/<int:basket_id>/',
        basket_remove,
        name='basket_remove'
    ),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    #path('auth/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe', stripe_webhook_view, name='webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordResetDoneView
from django.urls import path


from .views import (EmailVerificationView, UserLoginView, UserProfileView,
                    UserRegistrationView, UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordChange)

app_name = 'users'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path(
        'profile/<int:pk>/',
        login_required(UserProfileView.as_view()),
        name='profile'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'verify/<str:email>/<uuid:code>/',
        EmailVerificationView.as_view(),
        name='verify_email'
    ),
    path(
        'password_reset/',
        UserPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_email_done.html'
        ),
        name='password_reset_email'
    ),
    path(
        'reset/<uidb64>/<token>/',
        UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password_change',
        UserPasswordChange.as_view(),
        name='password_change'
    ),
]

store/products/models.py
import stripe
from _decimal import Decimal
from django.conf import settings
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.db import models

from users.models import User


stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField('Наименование', max_length=128, unique=True)
    description = models.TextField('Описание', null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    name = models.CharField('Наименование', max_length=256)
    description = models.TextField('Описание')
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField('Количество', default=0)
    stripe_product_price_id = models.CharField(
        max_length=128, null=True, blank=True
    )
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        related_name='category',
        verbose_name='Категория'
    )

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('-quantity',)

    def __str__(self) -> str:
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    # Перед сохранением добавляем новый продукт в бд stripe и заполняем наше
    # поле с id от stripe
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(
            force_insert=False, force_update=False, using=None,
            update_fields=None)

    # для онлайн оплаты, через пакет страйп создаем id продукта
    # его цену в бд stripe.
    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='rub'
        )
        return stripe_product_price


class Image(models.Model):
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        related_name='images'
    )
    image = models.ImageField('Изображение', upload_to='products_images')

    def __str__(self) -> str:
        return self.image.url


# расширяем метод QuerySet, добавляя к его методам нужные нам
class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        # self - это QuerySet к которму мы будем применять метод
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user',
        verbose_name='корзина'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product',
        verbose_name='товар'
    )
    quantity = models.PositiveSmallIntegerField(
        'Количество',
        default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    # переопределяем менеджер для обращений к классу баскет
    # теперь нам доступны методы все методы
    # QuerySet плюс total_sum и total_quantity
    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['created_timestamp']

    def __str__(self) -> str:
        return f'Корзина: {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return float(self.product.price) * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

store/products/forms.py
from django import forms
from .models import Product
from django.core.exceptions import ValidationError


class QuantityForm(forms.Form):
    product_id = forms.DecimalField(widget=forms.HiddenInput())
    quantity = forms.DecimalField(
        min_value=0,
        widget=forms.NumberInput()
        )

    def clean(self):
        cleaned_data = super().clean()
        product_id = cleaned_data.get('product_id')
        quantity = cleaned_data.get('quantity')
        product = Product.objects.get(id=product_id)
        if quantity > product.quantity:
            msg = f'Количество товара на складе {product.quantity}'
            self.add_error('quantity', msg)

store/products/common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context

store/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.urls import reverse

from products.common.views import TitleMixin
from products.models import Basket, Product, ProductCategory, Image


class IndexView(TitleMixin, TemplateView):
    a = 1
    template_name = 'products/index.html'
    title = 'Store'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - {self.object.name}'
        image = cache.get(f'image {self.object.id}')
        if not image:
            context['image'] = Image.objects.filter(product_id=self.object.id)
            cache.set(f'image {self.object.id}', context['image'], 30)
        else:
            context['image'] = image
        return context


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 6
    title = 'Store - Каталог'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        queryset = queryset.prefetch_related('images')
        category_id = self.kwargs.get('category_id')
        return (
            queryset.filter(category_id=category_id)
            if category_id else queryset
        )

# пример реализация кэша во вью
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        categories = cache.get('categories')
        if not categories:
            context['categories'] = ProductCategory.objects.all()
            cache.set('categories', context['categories'], 20)
        else:
            context['categories'] = categories
        return context



@login_required
def basket_add(request, product_id):

    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    quantity = int(request.POST['quantity'])

    # найти вариант решения (может полноценно через модел форм)
    # форма для валидации
    #form = QuantityForm(request.POST)
    #form.data = form.data.copy()
    #form.data['product_id'] = int(product.id)

    #form.data._mutable = True
    #form.data['product_id'] = product.id
    #form.data._mutable = False
    # if form.is_valid():
    if not baskets.exists():
        Basket.objects.create(
            user=request.user,
            product=product,
            quantity=quantity
        )
    else:
        basket = baskets.first()
        if basket.quantity + quantity <= product.quantity:
            basket.quantity += quantity
            basket.save()
        else:
            messages.info(
                request,
                f'Недопустимое количество товара.<br>'
                f'В корзине {basket.quantity} ед. указанного товара.<br>'
                f'Всего товара на складе: {product.quantity} ед.<br>'
                f'Можно добавить {product.quantity-basket.quantity} ед.'

            )
            return redirect(
                reverse('products:product_detail', kwargs={'pk': product.id})
            )
    return redirect(request.META['HTTP_REFERER'])


@login_required
def basket_update(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = get_object_or_404(Basket, user=request.user, product=product)
    quantity = request.POST['quantity']
    if not quantity:
        basket.delete()
    else:
        basket.quantity = int(quantity)
        basket.save()

    return redirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = get_object_or_404(Basket, id=basket_id)
    basket.delete()
    return redirect(request.META['HTTP_REFERER'])

store/products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href=" {% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index'%}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index'%}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href=" {% url 'orders:order_list' %}">Заказы</a></li>
                        {% if user.is_superuser or user.is_staff%}
                        <li><a class="dropdown-item" href="{% url 'admin:index'%}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}


{% block footer %} {% endblock %}


<!-- Bootstrap core JavaScript -->
<script src=" {% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src=" {% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src=" {% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/baskets.html
{% load humanize thumbnail %}

{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        <span class="text-primary">Корзина</span>
        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                       {% with basket.product.images.all|first as first_object %}
                               <a href="{% url 'products:product_detail' basket.product.id %}">
                                   <img width="100" height="100" src="{{ first_object.image.url }}">
                               </a>
                       {% endwith %}
                 </div>
                <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title; center-block">{{ basket.product.name }}</h5>
                    {# <p class="card-text">{{ basket.product.description }}</p> #}
                </div>
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-3; float-left">
                            <form id="form_update_basket" class="form-group" action="{% url 'products:basket_update' basket.product.id %}" method="post">
                                {% csrf_token %}
                                <input type="number" min="1" max="{{ basket.product.quantity }}" value="{{ basket.quantity }}" class="form-control" name="quantity" style="width: 95px">
                        </div>
                        <div class="col-lg-2">
                                <button class="btn-link" style="outline: none; border: none; background: none">
                                    <i class="fas fa-undo-alt"></i>
                                </button>
                            </form>
                        </div>
                        <div class="col-lg-4">{{ basket.sum|intcomma }} руб.</div>
                        <div class="col-lg-2">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum|intcomma }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-primary float-right" href="{% url 'orders:order_create' %}">
        Оформить заказ
    </a> <br>

{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}"  rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <!--    <div class="alert alert-light text-center" role="alert">-->
        <!--        Информационное сообщение-->
        <!--    </div>-->
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Store</h1>
                    <p>
                        Новые образы и лучшие бренды на Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
    {% if messages %}
        {{ messages }}
    {% endif %}
{% endblock %}

store/products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load static humanize thumbnail%}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
<div class="container">
    <div class="row">
            <div class="col-lg-7 col-md-6 mb-6">
                <div id="carouselExampleIndicators" class="carousel slide carousel-fade my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% with image|length as range %}
                        {% include 'includes/indicators.html' %}
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        {% if not image %}
                            <img class="card-img-top" height="500"
                                 src=" {% static 'vendor/img/products/отсутствует.png' %}"
                                 alt="">
                        {% endif %}
                        {% for img in image %}
                            {% if forloop.first %}
                                <div class="carousel-item active">
                                <img height="850" src="{{ img.image.url }}">
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                <img height="850" src="{{ img.image.url }}">
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% if range > 1 %}
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <i style="font-size: 30px; color: #17a2b8" class="fas fa-chevron-left"></i>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <i style="font-size: 30px; color: #17a2b8"  class="fas fa-chevron-right" ></i>
                        <span class="sr-only">Next</span>
                    </a>
                    {% endif %}
                </div>
            </div>
                 <div class="col-lg-5 col-md-6 mb-6">
                            <div class="card-body">
                                <h4 class="card-title">
                                     <b> {{ product.name }} </b>
                                </h4>
                                <h5> <b><i> Цена за ед.: </i></b> {{ product.price|intcomma }} руб. </h5>
                                <p class="card-text"> <h5> <b><i> Описание: </i></b> <br>  {{ product.description }} </h5> </p>
                                <p class="card-text"> <h5> <b><i> Количество товара на складе: </i></b>  {{ product.quantity }} ед.</h5> </p>
                                {% if messages  %}
                                    <div class="alert alert-info
                                    alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                                    {% for message in messages %}
                                        {% if forloop.first %}
                                        {{ message|safe }}
                                        {% endif %}
                                    {% endfor %}
                                    </div>
                                    {% endif %}
                            </div>
                            <div class="form-inline">
                                <form id="form_add_basket"  action="{% url 'products:basket_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="number" min="1" max="{{ product.quantity }}"  class="form-control" value="1"  name="quantity" style="width: 220px">
                                    <button type="submit" class="btn btn-info" style="width: 220px">
                                        Отправить в корзину
                                    </button>
                                 </form>
                             </div>
                 </div>
    </div>
</div>
    <!-- /.container -->
    {% endwith %}
{% endblock %}

store/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static humanize%}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/css/button.css' %}" rel="stylesheet">
{% endblock %}

{% block content %} 
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h2 class="my-4"> Store - Каталог</h2>
                <div class="list-group">
                    {% for category in categories %}
                            <a href="{% url 'products:category' category.id %}" class="list-group-item"> {{ category.name }} </a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                
                <div class="row">
                    {% for product in product_list %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="{% url 'products:product_detail' product.id %}">
                                <img class="card-img-top"
                                     {% with product.images.all|first as first_object %}
                                            src="{{ first_object.image.url }}"
                                            alt="">
                                        {% if not first_object %}
                                           <img class="card-img-top" width="200" height="290"
                                                src="{% static 'vendor/img/products/121_original.jpg' %}"
                                                alt="">
                                        {% endif %}
                                    {% endwith %}
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{% url 'products:product_detail' product.id %}"> {{ product.name }} </a>
                                </h4>
                                <h5> {{ product.price|intcomma }} руб. </h5>
                                <p class="card-text"> {{ product.description }} </p>
                            </div>
                            <div class="form-inline">
                                <form id="form_add_basket" class="form-group" action="{% url 'products:basket_add' product.id %}" method="post">
                                    {% csrf_token %}

                                    <input type="number" min="1" max="{{ product.quantity }}"  value="1" class="form-control" name="quantity" style="width: 74px">

                                    <button type="submit" class="btn btn-outline-success" style="width: 181px">
                                        Отправить в корзину
                                    </button>
                                 </form>
                             </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% include "includes/paginator.html"%}
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}