store/api/urls.py
from django.urls import include, path


app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    #path('auth/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe', stripe_webhook_view, name='webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, PasswordResetDoneView
from django.urls import path


from .views import (EmailVerificationView, UserLoginView, UserProfileView,
                    UserRegistrationView, UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordChange)

app_name = 'users'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path(
        'profile/<int:pk>/',
        login_required(UserProfileView.as_view()),
        name='profile'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path(
        'verify/<str:email>/<uuid:code>/',
        EmailVerificationView.as_view(),
        name='verify_email'
    ),
    path(
        'password_reset/',
        UserPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_email_done.html'
        ),
        name='password_reset_email'
    ),
    path(
        'reset/<uidb64>/<token>/',
        UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password_change',
        UserPasswordChange.as_view(),
        name='password_change'
    ),
]

store/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    email = models.EmailField('email address', unique=True)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    # формирует уникальный код
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification for {self.user.email}'

    def send_verification_email(self):
        # формируем ссылку по которой пользователь должен перейти
        link = reverse(
            'users:verify_email',
            kwargs={'email': self.user.email, 'code': self.code}
        )
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Для подтверждения учетной записи перейдите по ссылку: {}'\
            .format(
                verification_link
            )
        # отправляем сообщение с сформированной ссылкой,
        # перейдя по ней, отработает контроллер
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        # проверят текущее время с утановленным сроком действия кода
        return now() >= self.expiration

store/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm, PasswordResetForm, SetPasswordForm)

from .models import User
from .tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя пользователя',
        }
        )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите пароль',
        }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя',
        }
        )
    )
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите фамилию',
        }
        )
    )
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите имя пользователя',
        }
        )
    )
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите адрес эл. почты',
        }
        )
    )
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Введите пароль',
        }
        )
    )
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control py-4',
            'placeholder': 'Подтвердите пароль',
        }
        )
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
        }
        )
    )
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
        }
        )
    )
    image = forms.ImageField(widget=forms.FileInput(
        attrs={
            'class': 'custom-file-label',
        }
        ), required=False
    )
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control py-4',
            'readonly': True
        }
        )
    )
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control py-4',
            'readonly': True
        }
        ), required=False
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'image',
            'username',
            'email'
        )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.CharField(
        help_text='Забыли пароль? Введите свой адрес электронной почты,'
                  ' и мы вышлем вам инструкцию, как установить новый пароль.',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control py-4',
                'autocomplete': 'email',
                'placeholder': 'Введите адрес электронной почты',
            }
        ),

    )


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'form-control py-4',
                'placeholder': 'Введите пароль',
            }
        ),
        strip=False,
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'form-control py-4',
                'placeholder': 'Введите пароль повторно',
            }
        ),
    )

store/users/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordChangeView
from products.common.views import TitleMixin
from django.contrib import messages

from django.conf import settings


from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm, UserPasswordResetForm, UserSetPasswordForm
from .models import EmailVerification, User


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Store - Авторизация'


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Подзравляем! Вы успешно зарегистрировались.'
    title = 'Store - Регистрация'


# найти красивое решение, если в адрессной строке набрать чужой id
# как обработать эту ситуацию
# сейчас проверка в шаблоне
class UserProfileView(TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Store - Личный кабинет'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))

    # переменную baskets определил глобально в контекс процес..
    # def get_context_data(self, **kwargs):
    #     context = super(UserProfileView, self).get_context_data()
    #     context['baskets'] = Basket.objects.filter(user=self.object)
    #     return context


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Store - подтверждение электронной почты'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        # пользователь переходя по сформированной нами ссылке передает
        # email и uuid code
        code = kwargs['code']
        # достаем юзера по мылу (уникальное поле)
        user = User.objects.get(email=kwargs['email'])
        # из модели получаем нужный объект
        email_verification = EmailVerification.objects.filter(
            user=user,
            code=code
        )
        # если объект существует и код не устарел (2 суток) сохраняем изменения
        # булевая переменная переходит в статус True
        if email_verification.exists()\
                and not email_verification.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(
                EmailVerificationView, self
            ).get(request, *args, **kwargs)
        return redirect(reverse('index'))


class UserPasswordResetView(PasswordResetView):
    form_class = UserPasswordResetForm
    title = "Store - восстановление пароля"
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_email')
    from_email = settings.EMAIL_HOST_USER


class UserPasswordResetConfirmView(
    SuccessMessageMixin, PasswordResetConfirmView
):
    title = "Store - смена пароля"
    template_name = 'users/password_reset_confirm.html'
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('users:login')
    success_message = 'Ваш пароль был сохранен. Теперь вы можете войти.'


class UserPasswordChange(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/profile.html'
    success_message = 'Ваш пароль изменен'

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.error(self.request, 'Ваш пароль НЕ изменен.<br>'
                                     'При изменении пароля руководствуйтесь инструкцией в форме.')
        return redirect(reverse('users:profile', args=(self.request.user.id,)))

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.request.user.id,))

store/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title> {{ title }} </title>
    <link href="{% static 'vendor/css/auth.css'%}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js'%}"></script>
</body>
</html>

store/users/templates/users/email_verification.html
{% extends 'users/base.html'%}
{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>Ваша учетная запись успешно подтверждена!</h4>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Продолжить</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% endblock %}

store/users/templates/users/login.html
{% extends 'users/base.html'%}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if messages or form.non_field_errors %}
                    <div class="alert
                    {% if messages %} alert-success {% else %} alert-warning {% endif %}
                    alert-dismissible fade show" role="alert"
                        style="margin-top: 50px;">
                        {% if messages %}
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        {% else %}
                            {{ form.non_field_errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3></div>
                    <div class="card-body">
                        <form action="{% url 'users:login' %}" method='post'>
                            {% csrf_token %} 
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                {{ form.password }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                                <input class="btn btn-primary" type="submit" value="Авторизоваться"></div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a href="#">
                                    <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-telegram fa-2x" style="color: #303030;"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                </a>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

store/users/templates/users/password_change.html
<div style="margin-top: 15px;">
    <p>
  <button class="btn btn-outline-info" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample" style="font-size: small">
    Изменить пароль
  </button>
</p>
    <div class="col-12">
        <div style="min-height: 120px;">
            <div class="collapse collapse-horizontal" id="collapseWidthExample">
                <div class="mt-6">
                    <form action=" {% url 'users:password_change' %}" method='post'>
                        {% csrf_token %}
                        <div class="form-group row my-3 p-3">
                            <label for="id_old_password">
                                Старый пароль
                                <span class="required text-danger">*</span>
                            </label>
                            <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                        </div>
                        <div class="form-group row my-3 p-3">
                            <label for="id_new_password1">
                                Новый пароль
                                <span class="required text-danger">*</span>
                            </label>
                            <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                            <small id="id_new_password1-help" class="form-text text-muted">
                                <ul>
                                    <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                                    <li>Ваш пароль не может состоять только из цифр.</li>
                                </ul>
                            </small>
                        </div>
                        <div class="form-group row my-3 p-3">
                            <label for="id_new_password2">
                                Подтверждение нового пароля
                                <span class="required text-danger">*</span>
                            </label>
                            <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                        </div>
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-info" style="font-size: small">
                                Изменить пароль
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

store/users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}


{% block content %}
    {% if validlink %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Введите новый пароль</h3>
                        <div class="text-center">
                            Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.
                        </div>
                    <div class="card-body">
                         <form action="" method='post'>
                             {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.new_password1.id_for_label }}">Новый пароль:</label>
                                {{ form.new_password1 }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.new_password2.id_for_label }}">Подтвердите пароль:</label>
                                {{ form.new_password2 }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <input class="btn btn-primary" type="submit" value="Изменить мой пароль"></div>
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
    {% else %}
 <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Ошибка</h3>
                    <div class="card-body">
                        <div class="text-center">
                            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
 </div>
{% endif %}
{% endblock %}

store/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

store/users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}


{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Восстановление пароля</h3>
                    <div class="card-body">
                        <form action="{% url 'users:password_reset' %}" method='post'>
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}"></label>
                                {{ form.email }}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ form.email.help_text|safe }}
                                </small>
                            </div>
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="{% url 'users:login' %}">Вернуться к авторизации?</a>
                                <input class="btn btn-primary" type="submit" value="Восстановить мой пароль">
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</main>
{% endblock %}

store/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
   <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors%}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                                style="margin-top: 50px;">
                                {{ form.errors }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:registration' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                    {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}