store/api/urls.py
from django.urls import include, path


app_name = 'api'

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

store/products/urls.py
from django.urls import path

from .views import ProductsListView, ProductDetailView, basket_add, basket_update, basket_remove

app_name = 'products'


urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('page/<int:page>/', ProductsListView.as_view(), name='paginator'),
    path(
        'category/<int:category_id>/',
        ProductsListView.as_view(),
        name='category'
    ),
    path(
        'baskets/add/<int:product_id>/',
        basket_add,
        name='basket_add'
    ),
    path(
        'baskets/update/<int:product_id>/',
        basket_update,
        name='basket_update'
    ),
    path(
        'baskets/remove/<int:basket_id>/',
        basket_remove,
        name='basket_remove'
    ),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from orders.views import stripe_webhook_view
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    #path('auth/', include('django.contrib.auth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe', stripe_webhook_view, name='webhook'),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

store/products/models.py
import stripe
from _decimal import Decimal
from django.conf import settings
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.db import models

from users.models import User


stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField('Наименование', max_length=128, unique=True)
    description = models.TextField('Описание', null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    name = models.CharField('Наименование', max_length=256)
    description = models.TextField('Описание')
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField('Количество', default=0)
    stripe_product_price_id = models.CharField(
        max_length=128, null=True, blank=True
    )
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        related_name='category',
        verbose_name='Категория'
    )

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('-quantity',)

    def __str__(self) -> str:
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    # Перед сохранением добавляем новый продукт в бд stripe и заполняем наше
    # поле с id от stripe
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(
            force_insert=False, force_update=False, using=None,
            update_fields=None)

    # для онлайн оплаты, через пакет страйп создаем id продукта
    # его цену в бд stripe.
    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='rub'
        )
        return stripe_product_price


class Image(models.Model):
    product = models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        related_name='images'
    )
    image = models.ImageField('Изображение', upload_to='products_images')

    def __str__(self) -> str:
        return self.image.url


# расширяем метод QuerySet, добавляя к его методам нужные нам
class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        # self - это QuerySet к которму мы будем применять метод
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user',
        verbose_name='корзина'
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='product',
        verbose_name='товар'
    )
    quantity = models.PositiveSmallIntegerField(
        'Количество',
        default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    # переопределяем менеджер для обращений к классу баскет
    # теперь нам доступны методы все методы
    # QuerySet плюс total_sum и total_quantity
    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ['created_timestamp']

    def __str__(self) -> str:
        return f'Корзина: {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return float(self.product.price) * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_item

store/products/forms.py
from django import forms
from .models import Product
from django.core.exceptions import ValidationError


class QuantityForm(forms.Form):
    product_id = forms.DecimalField(widget=forms.HiddenInput())
    quantity = forms.DecimalField(
        min_value=0,
        widget=forms.NumberInput()
        )

    def clean(self):
        cleaned_data = super().clean()
        product_id = cleaned_data.get('product_id')
        quantity = cleaned_data.get('quantity')
        product = Product.objects.get(id=product_id)
        if quantity > product.quantity:
            msg = f'Количество товара на складе {product.quantity}'
            self.add_error('quantity', msg)

store/products/common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context

store/products/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.urls import reverse

from products.common.views import TitleMixin
from products.models import Basket, Product, ProductCategory, Image


class IndexView(TitleMixin, TemplateView):
    a = 1
    template_name = 'products/index.html'
    title = 'Store'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Store - {self.object.name}'
        image = cache.get(f'image {self.object.id}')
        if not image:
            context['image'] = Image.objects.filter(product_id=self.object.id)
            cache.set(f'image {self.object.id}', context['image'], 30)
        else:
            context['image'] = image
        return context


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 6
    title = 'Store - Каталог'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        queryset = queryset.prefetch_related('images')
        category_id = self.kwargs.get('category_id')
        return (
            queryset.filter(category_id=category_id)
            if category_id else queryset
        )

# пример реализация кэша во вью
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        categories = cache.get('categories')
        if not categories:
            context['categories'] = ProductCategory.objects.all()
            cache.set('categories', context['categories'], 20)
        else:
            context['categories'] = categories
        return context



@login_required
def basket_add(request, product_id):

    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    quantity = int(request.POST['quantity'])

    # найти вариант решения (может полноценно через модел форм)
    # форма для валидации
    #form = QuantityForm(request.POST)
    #form.data = form.data.copy()
    #form.data['product_id'] = int(product.id)

    #form.data._mutable = True
    #form.data['product_id'] = product.id
    #form.data._mutable = False
    # if form.is_valid():
    if not baskets.exists():
        Basket.objects.create(
            user=request.user,
            product=product,
            quantity=quantity
        )
    else:
        basket = baskets.first()
        if basket.quantity + quantity <= product.quantity:
            basket.quantity += quantity
            basket.save()
        else:
            messages.info(
                request,
                f'Недопустимое количество товара.<br>'
                f'В корзине {basket.quantity} ед. указанного товара.<br>'
                f'Всего товара на складе: {product.quantity} ед.<br>'
                f'Можно добавить {product.quantity-basket.quantity} ед.'

            )
            return redirect(
                reverse('products:product_detail', kwargs={'pk': product.id})
            )
    return redirect(request.META['HTTP_REFERER'])


@login_required
def basket_update(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = get_object_or_404(Basket, user=request.user, product=product)
    quantity = request.POST['quantity']
    if not quantity:
        basket.delete()
    else:
        basket.quantity = int(quantity)
        basket.save()

    return redirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = get_object_or_404(Basket, id=basket_id)
    basket.delete()
    return redirect(request.META['HTTP_REFERER'])

store/products/templates/includes/footer.html
    <!-- Footer -->
    <footer class="py-3 bg-dark">

        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store {{ year }}</p>
        </div>

        <!-- /.container -->
    </footer>

store/products/templates/includes/indicators.html
{% if range == 1 %}
{% elif range == 2 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
{% elif range == 3 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
{% elif range == 4 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
{% elif range == 5 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
{% endif %}

store/products/templates/includes/paginator.html
                    </div>
                    {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                                href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %}{% else %} # {% endif %}"
                                tabindex="-1" aria-disabled="true">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% for page in paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link" href=" {% url 'products:paginator' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                            <a class="page-link"
                                href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        
                        </li>
                    </ul>
                    </nav>
                 {% endif %}
                </div>